// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Windows_22120278_Data;

#nullable disable

namespace Windows_22120278_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206140533_LinkTemplatesToProfile")]
    partial class LinkTemplatesToProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Windows_22120278_Data.models.DrawingBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("DrawingBoards");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultBoardHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultBoardWidth")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefaultThemeDark")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.ShapeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("DrawingBoardId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EndX")
                        .HasColumnType("REAL");

                    b.Property<double>("EndY")
                        .HasColumnType("REAL");

                    b.Property<string>("PointsData")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartX")
                        .HasColumnType("REAL");

                    b.Property<double>("StartY")
                        .HasColumnType("REAL");

                    b.Property<double>("StrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrawingBoardId");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.ShapeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndX")
                        .HasColumnType("REAL");

                    b.Property<double>("EndY")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PointsData")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartX")
                        .HasColumnType("REAL");

                    b.Property<double>("StartY")
                        .HasColumnType("REAL");

                    b.Property<double>("StrokeThickness")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ShapeTemplates");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.DrawingBoard", b =>
                {
                    b.HasOne("Windows_22120278_Data.models.Profile", "Profile")
                        .WithMany("DrawingBoards")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.ShapeEntity", b =>
                {
                    b.HasOne("Windows_22120278_Data.models.DrawingBoard", "DrawingBoard")
                        .WithMany("Shapes")
                        .HasForeignKey("DrawingBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DrawingBoard");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.ShapeTemplate", b =>
                {
                    b.HasOne("Windows_22120278_Data.models.Profile", "Profile")
                        .WithMany("ShapeTemplates")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.DrawingBoard", b =>
                {
                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("Windows_22120278_Data.models.Profile", b =>
                {
                    b.Navigation("DrawingBoards");

                    b.Navigation("ShapeTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
